spring:
  application:
    name: it-crowd

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/it-crowd-h2-db
    username: sa

  jpa:
    hibernate:
      ddl-auto: update

  ai:
    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
