version: "3.9"
services:
  ollama:
    restart: unless-stopped
    image: ollama/ollama
    networks:
      - it-crowd

  it-crowd:
    restart: unless-stopped
    container_name: it-crowd
    depends_on:
      - ollama
    build:
      context: ../
      dockerfile: multi_docker/Dockerfile_crowd
    environment:
      OLLAMA_URL: http://ollama:11434
    ports:
      - "8080:8080"
    networks:
      - it-crowd

networks:
  it-crowd:
    driver: bridge
